import { readFile } from 'fs/promises';
import path from 'path';

export interface PamChangelogRelease {
  version: string;
  /** Markdown body under the `## <version>` heading. */
  body: string;
}

export interface PamChangelogEntry {
  /** `####` heading without the leading emoji, e.g. `Features`. */
  category: string;
  scope: string | null;
  text: string;
}

/**
 * Reads `apps/pam/CHANGELOG.md` (generated by the release tooling) and splits
 * it into releases, newest first. Read at build time (the page is SSG).
 */
export async function readPamChangelog(): Promise<PamChangelogRelease[]> {
  const candidates = [
    path.join(process.cwd(), 'CHANGELOG.md'),
    path.join(process.cwd(), 'apps', 'pam', 'CHANGELOG.md')
  ];
  for (const file of candidates) {
    try {
      return parsePamChangelog(await readFile(file, 'utf8'));
    } catch {
      // try the next candidate
    }
  }
  throw new Error('pam CHANGELOG.md not found');
}

export function parsePamChangelog(markdown: string): PamChangelogRelease[] {
  const releases: PamChangelogRelease[] = [];
  let current: PamChangelogRelease | null = null;
  const lines: string[] = [];

  const flush = () => {
    if (current) {
      current.body = lines.join('\n').trim();
      releases.push(current);
    }
    lines.length = 0;
  };

  for (const line of markdown.replace(/\r\n/g, '\n').split('\n')) {
    const heading = /^##\s+(.+?)\s*$/.exec(line);
    if (heading) {
      flush();
      current = { version: heading[1]!, body: '' };
      continue;
    }
    if (current) {
      lines.push(line);
    }
  }
  flush();

  return releases;
}

/**
 * Top-level bullets of a release as plain text (commit / PR links stripped).
 */
export function summarizePamChangelogRelease(
  body: string
): PamChangelogEntry[] {
  const entries: PamChangelogEntry[] = [];
  let category = '';

  for (const line of body.split('\n')) {
    const heading = /^####\s+(.+?)\s*$/.exec(line);
    if (heading) {
      category = heading[1]!.replace(/^[^\p{L}]+/u, '');
      continue;
    }
    const bullet = /^- (.+)$/.exec(line);
    if (!bullet) {
      continue;
    }
    let text = bullet[1]!
      .replace(/\s*\(\[[^\]]*\]\([^)]*\)\)/g, '')
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .trim();
    let scope: string | null = null;
    const scoped = /^\*\*([^*]+?):\*\*\s*(.*)$/.exec(text);
    if (scoped) {
      scope = scoped[1]!;
      text = scoped[2]!;
    }
    if (text) {
      entries.push({ category, scope, text });
    }
  }

  return entries;
}
