/**
 * Auto-generated by tools/generateApiRoutes.ts — do not edit manually.
 *
 * **Jump to handler:** hover the symbol → in the JSDoc popup, click *Open route handler*.
 * If the link fails, use Quick Open (Ctrl/Cmd+P) with the path on the last JSDoc line.
 */

/**
 * API path: `/api/admin/overview`
 *
 * @see [src/app/api/admin/overview/route.ts](../../src/app/api/admin/overview/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/admin/overview/route.ts`
 */
export const API_ADMIN_OVERVIEW = '/api/admin/overview' as const;

/**
 * API path: `/api/admin/site-settings`
 *
 * @see [src/app/api/admin/site-settings/route.ts](../../src/app/api/admin/site-settings/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/admin/site-settings/route.ts`
 */
export const API_ADMIN_SITE_SETTINGS = '/api/admin/site-settings' as const;

/**
 * API path: `/api/admin/users`
 *
 * @see [src/app/api/admin/users/route.ts](../../src/app/api/admin/users/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/admin/users/route.ts`
 */
export const API_ADMIN_USERS = '/api/admin/users' as const;

/**
 * API path: `/api/clients`
 *
 * @see [src/app/api/clients/route.ts](../../src/app/api/clients/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/route.ts`
 */
export const API_CLIENTS = '/api/clients' as const;

/**
 * API path: `/api/clients/:clientId`
 *
 * @see [src/app/api/clients/[clientId]/route.ts](../../src/app/api/clients/[clientId]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/[clientId]/route.ts`
 */
export const API_CLIENTS_2 = '/api/clients/:clientId' as const;

/**
 * API path: `/api/clients/:clientId/rotate-secret`
 *
 * @see [src/app/api/clients/[clientId]/rotate-secret/route.ts](../../src/app/api/clients/[clientId]/rotate-secret/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/[clientId]/rotate-secret/route.ts`
 */
export const API_CLIENTS_ROTATE_SECRET =
  '/api/clients/:clientId/rotate-secret' as const;

/**
 * API path: `/api/oauth/authorize-preview`
 *
 * @see [src/app/api/oauth/authorize-preview/route.ts](../../src/app/api/oauth/authorize-preview/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/authorize-preview/route.ts`
 */
export const API_OAUTH_AUTHORIZE_PREVIEW =
  '/api/oauth/authorize-preview' as const;

/**
 * API path: `/api/oauth/consent`
 *
 * @see [src/app/api/oauth/consent/route.ts](../../src/app/api/oauth/consent/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/consent/route.ts`
 */
export const API_OAUTH_CONSENT = '/api/oauth/consent' as const;

/**
 * API path: `/api/oauth/playground/validate`
 *
 * @see [src/app/api/oauth/playground/validate/route.ts](../../src/app/api/oauth/playground/validate/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/playground/validate/route.ts`
 */
export const API_OAUTH_PLAYGROUND_VALIDATE =
  '/api/oauth/playground/validate' as const;

/**
 * API path: `/api/oauth/verify`
 *
 * @see [src/app/api/oauth/verify/route.ts](../../src/app/api/oauth/verify/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/verify/route.ts`
 */
export const API_OAUTH_VERIFY = '/api/oauth/verify' as const;

/**
 * API path: `/api/reference`
 *
 * @see [src/app/api/reference/route.ts](../../src/app/api/reference/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/reference/route.ts`
 */
export const API_REFERENCE = '/api/reference' as const;

/**
 * API path: `/api/user/login`
 *
 * @see [src/app/api/user/login/route.ts](../../src/app/api/user/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/route.ts`
 */
export const API_USER_LOGIN = '/api/user/login' as const;

/**
 * API path: `/api/user/logout`
 *
 * @see [src/app/api/user/logout/route.ts](../../src/app/api/user/logout/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/logout/route.ts`
 */
export const API_USER_LOGOUT = '/api/user/logout' as const;

/**
 * API path: `/api/user/otp/login`
 *
 * @see [src/app/api/user/otp/login/route.ts](../../src/app/api/user/otp/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/login/route.ts`
 */
export const API_USER_OTP_LOGIN = '/api/user/otp/login' as const;

/**
 * API path: `/api/user/otp/verify`
 *
 * @see [src/app/api/user/otp/verify/route.ts](../../src/app/api/user/otp/verify/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/verify/route.ts`
 */
export const API_USER_OTP_VERIFY = '/api/user/otp/verify' as const;

/**
 * API path: `/api/user/request-logs`
 *
 * @see [src/app/api/user/request-logs/route.ts](../../src/app/api/user/request-logs/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/request-logs/route.ts`
 */
export const API_USER_REQUEST_LOGS = '/api/user/request-logs' as const;

/**
 * API path: `/api/user/session`
 *
 * @see [src/app/api/user/session/route.ts](../../src/app/api/user/session/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/session/route.ts`
 */
export const API_USER_SESSION = '/api/user/session' as const;

export type ApiRoutePath =
  | typeof API_ADMIN_OVERVIEW
  | typeof API_ADMIN_SITE_SETTINGS
  | typeof API_ADMIN_USERS
  | typeof API_CLIENTS
  | typeof API_CLIENTS_2
  | typeof API_CLIENTS_ROTATE_SECRET
  | typeof API_OAUTH_AUTHORIZE_PREVIEW
  | typeof API_OAUTH_CONSENT
  | typeof API_OAUTH_PLAYGROUND_VALIDATE
  | typeof API_OAUTH_VERIFY
  | typeof API_REFERENCE
  | typeof API_USER_LOGIN
  | typeof API_USER_LOGOUT
  | typeof API_USER_OTP_LOGIN
  | typeof API_USER_OTP_VERIFY
  | typeof API_USER_REQUEST_LOGS
  | typeof API_USER_SESSION;
