/**
 * Auto-generated by tools/generateApiRoutes.ts — do not edit manually.
 *
 * **Jump to handler:** hover the symbol → in the JSDoc popup, click *Open route handler*.
 * If the link fails, use Quick Open (Ctrl/Cmd+P) with the path on the last JSDoc line.
 */

/**
 * API path: `/api/callback/brain-oauth`
 *
 * @see [src/app/api/callback/brain-oauth/route.ts](../../src/app/api/callback/brain-oauth/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/brain-oauth/route.ts`
 */
export const API_CALLBACK_BRAIN_OAUTH = '/api/callback/brain-oauth' as const;

/**
 * API path: `/api/callback/email-login`
 *
 * @see [src/app/api/callback/email-login/route.ts](../../src/app/api/callback/email-login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/email-login/route.ts`
 */
export const API_CALLBACK_EMAIL_LOGIN = '/api/callback/email-login' as const;

/**
 * API path: `/api/callback/provider-login`
 *
 * @see [src/app/api/callback/provider-login/route.ts](../../src/app/api/callback/provider-login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/callback/provider-login/route.ts`
 */
export const API_CALLBACK_PROVIDER_LOGIN =
  '/api/callback/provider-login' as const;

/**
 * API path: `/api/clients`
 *
 * @see [src/app/api/clients/route.ts](../../src/app/api/clients/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/route.ts`
 */
export const API_CLIENTS = '/api/clients' as const;

/**
 * API path: `/api/clients/:clientId`
 *
 * @see [src/app/api/clients/[clientId]/route.ts](../../src/app/api/clients/[clientId]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/[clientId]/route.ts`
 */
export const API_CLIENTS_2 = '/api/clients/:clientId' as const;

/**
 * API path: `/api/clients/:clientId/rotate-secret`
 *
 * @see [src/app/api/clients/[clientId]/rotate-secret/route.ts](../../src/app/api/clients/[clientId]/rotate-secret/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/clients/[clientId]/rotate-secret/route.ts`
 */
export const API_CLIENTS_ROTATE_SECRET =
  '/api/clients/:clientId/rotate-secret' as const;

/**
 * API path: `/api/locales/json`
 *
 * @see [src/app/api/locales/json/route.ts](../../src/app/api/locales/json/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/locales/json/route.ts`
 */
export const API_LOCALES_JSON = '/api/locales/json' as const;

/**
 * API path: `/api/oauth/consent`
 *
 * @see [src/app/api/oauth/consent/route.ts](../../src/app/api/oauth/consent/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/consent/route.ts`
 */
export const API_OAUTH_CONSENT = '/api/oauth/consent' as const;

/**
 * API path: `/api/oauth/playground/validate`
 *
 * @see [src/app/api/oauth/playground/validate/route.ts](../../src/app/api/oauth/playground/validate/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/playground/validate/route.ts`
 */
export const API_OAUTH_PLAYGROUND_VALIDATE =
  '/api/oauth/playground/validate' as const;

/**
 * API path: `/api/oauth/verify`
 *
 * @see [src/app/api/oauth/verify/route.ts](../../src/app/api/oauth/verify/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/oauth/verify/route.ts`
 */
export const API_OAUTH_VERIFY = '/api/oauth/verify' as const;

/**
 * API path: `/api/pam/:projectId/environments`
 *
 * @see [src/app/api/pam/[projectId]/environments/route.ts](../../src/app/api/pam/[projectId]/environments/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/[projectId]/environments/route.ts`
 */
export const API_PAM_ENVIRONMENTS = '/api/pam/:projectId/environments' as const;

/**
 * API path: `/api/pam/:projectId/environments/:envId/delete`
 *
 * @see [src/app/api/pam/[projectId]/environments/[envId]/delete/route.ts](../../src/app/api/pam/[projectId]/environments/[envId]/delete/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/[projectId]/environments/[envId]/delete/route.ts`
 */
export const API_PAM_ENVIRONMENTS_DELETE =
  '/api/pam/:projectId/environments/:envId/delete' as const;

/**
 * API path: `/api/pam/:projectId/environments/:envId/export`
 *
 * @see [src/app/api/pam/[projectId]/environments/[envId]/export/route.ts](../../src/app/api/pam/[projectId]/environments/[envId]/export/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/[projectId]/environments/[envId]/export/route.ts`
 */
export const API_PAM_ENVIRONMENTS_EXPORT =
  '/api/pam/:projectId/environments/:envId/export' as const;

/**
 * API path: `/api/pam/:projectId/environments/:envId/variables`
 *
 * @see [src/app/api/pam/[projectId]/environments/[envId]/variables/route.ts](../../src/app/api/pam/[projectId]/environments/[envId]/variables/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/[projectId]/environments/[envId]/variables/route.ts`
 */
export const API_PAM_ENVIRONMENTS_VARIABLES =
  '/api/pam/:projectId/environments/:envId/variables' as const;

/**
 * API path: `/api/pam/categories`
 *
 * @see [src/app/api/pam/categories/route.ts](../../src/app/api/pam/categories/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/categories/route.ts`
 */
export const API_PAM_CATEGORIES = '/api/pam/categories' as const;

/**
 * API path: `/api/pam/cli/device/approve`
 *
 * @see [src/app/api/pam/cli/device/approve/route.ts](../../src/app/api/pam/cli/device/approve/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/cli/device/approve/route.ts`
 */
export const API_PAM_CLI_DEVICE_APPROVE =
  '/api/pam/cli/device/approve' as const;

/**
 * API path: `/api/pam/cli/device/code`
 *
 * @see [src/app/api/pam/cli/device/code/route.ts](../../src/app/api/pam/cli/device/code/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/cli/device/code/route.ts`
 */
export const API_PAM_CLI_DEVICE_CODE = '/api/pam/cli/device/code' as const;

/**
 * API path: `/api/pam/cli/device/token`
 *
 * @see [src/app/api/pam/cli/device/token/route.ts](../../src/app/api/pam/cli/device/token/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/cli/device/token/route.ts`
 */
export const API_PAM_CLI_DEVICE_TOKEN = '/api/pam/cli/device/token' as const;

/**
 * API path: `/api/pam/cli/logout`
 *
 * @see [src/app/api/pam/cli/logout/route.ts](../../src/app/api/pam/cli/logout/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/cli/logout/route.ts`
 */
export const API_PAM_CLI_LOGOUT = '/api/pam/cli/logout' as const;

/**
 * API path: `/api/pam/cli/token`
 *
 * @see [src/app/api/pam/cli/token/route.ts](../../src/app/api/pam/cli/token/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/cli/token/route.ts`
 */
export const API_PAM_CLI_TOKEN = '/api/pam/cli/token' as const;

/**
 * API path: `/api/pam/create`
 *
 * @see [src/app/api/pam/create/route.ts](../../src/app/api/pam/create/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/create/route.ts`
 */
export const API_PAM_CREATE = '/api/pam/create' as const;

/**
 * API path: `/api/pam/delete/:id`
 *
 * @see [src/app/api/pam/delete/[id]/route.ts](../../src/app/api/pam/delete/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/delete/[id]/route.ts`
 */
export const API_PAM_DELETE = '/api/pam/delete/:id' as const;

/**
 * API path: `/api/pam/detail/:id`
 *
 * @see [src/app/api/pam/detail/[id]/route.ts](../../src/app/api/pam/detail/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/detail/[id]/route.ts`
 */
export const API_PAM_DETAIL = '/api/pam/detail/:id' as const;

/**
 * API path: `/api/pam/edit/:id`
 *
 * @see [src/app/api/pam/edit/[id]/route.ts](../../src/app/api/pam/edit/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/edit/[id]/route.ts`
 */
export const API_PAM_EDIT = '/api/pam/edit/:id' as const;

/**
 * API path: `/api/pam/fork/:id`
 *
 * @see [src/app/api/pam/fork/[id]/route.ts](../../src/app/api/pam/fork/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/fork/[id]/route.ts`
 */
export const API_PAM_FORK = '/api/pam/fork/:id' as const;

/**
 * API path: `/api/pam/search`
 *
 * @see [src/app/api/pam/search/route.ts](../../src/app/api/pam/search/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/search/route.ts`
 */
export const API_PAM_SEARCH = '/api/pam/search' as const;

/**
 * API path: `/api/pam/transfer/:id`
 *
 * @see [src/app/api/pam/transfer/[id]/route.ts](../../src/app/api/pam/transfer/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/transfer/[id]/route.ts`
 */
export const API_PAM_TRANSFER = '/api/pam/transfer/:id' as const;

/**
 * API path: `/api/pam/users/search`
 *
 * @see [src/app/api/pam/users/search/route.ts](../../src/app/api/pam/users/search/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/users/search/route.ts`
 */
export const API_PAM_USERS_SEARCH = '/api/pam/users/search' as const;

/**
 * API path: `/api/pam/preview-image/:id`
 *
 * @see [src/app/api/pam/preview-image/[id]/route.ts](../../src/app/api/pam/preview-image/[id]/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/pam/preview-image/[id]/route.ts`
 */
export const API_PAM_PREVIEW_IMAGE = '/api/pam/preview-image/:id' as const;

/**
 * API path: `/api/reference`
 *
 * @see [src/app/api/reference/route.ts](../../src/app/api/reference/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/reference/route.ts`
 */
export const API_REFERENCE = '/api/reference' as const;

/**
 * API path: `/api/user/login`
 *
 * @see [src/app/api/user/login/route.ts](../../src/app/api/user/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/route.ts`
 */
export const API_USER_LOGIN = '/api/user/login' as const;

/**
 * API path: `/api/user/login/brain`
 *
 * @see [src/app/api/user/login/brain/route.ts](../../src/app/api/user/login/brain/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/brain/route.ts`
 */
export const API_USER_LOGIN_BRAIN = '/api/user/login/brain' as const;

/**
 * API path: `/api/user/login/provider`
 *
 * @see [src/app/api/user/login/provider/route.ts](../../src/app/api/user/login/provider/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/login/provider/route.ts`
 */
export const API_USER_LOGIN_PROVIDER = '/api/user/login/provider' as const;

/**
 * API path: `/api/user/logout`
 *
 * @see [src/app/api/user/logout/route.ts](../../src/app/api/user/logout/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/logout/route.ts`
 */
export const API_USER_LOGOUT = '/api/user/logout' as const;

/**
 * API path: `/api/user/otp/login`
 *
 * @see [src/app/api/user/otp/login/route.ts](../../src/app/api/user/otp/login/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/login/route.ts`
 */
export const API_USER_OTP_LOGIN = '/api/user/otp/login' as const;

/**
 * API path: `/api/user/otp/verify`
 *
 * @see [src/app/api/user/otp/verify/route.ts](../../src/app/api/user/otp/verify/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/otp/verify/route.ts`
 */
export const API_USER_OTP_VERIFY = '/api/user/otp/verify' as const;

/**
 * API path: `/api/user/register`
 *
 * @see [src/app/api/user/register/route.ts](../../src/app/api/user/register/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/register/route.ts`
 */
export const API_USER_REGISTER = '/api/user/register' as const;

/**
 * API path: `/api/user/request-logs`
 *
 * @see [src/app/api/user/request-logs/route.ts](../../src/app/api/user/request-logs/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/request-logs/route.ts`
 */
export const API_USER_REQUEST_LOGS = '/api/user/request-logs' as const;

/**
 * API path: `/api/user/session`
 *
 * @see [src/app/api/user/session/route.ts](../../src/app/api/user/session/route.ts)
 *
 * **Fallback:** Ctrl/Cmd+P (Quick Open) → `src/app/api/user/session/route.ts`
 */
export const API_USER_SESSION = '/api/user/session' as const;

export type ApiRoutePath =
  | typeof API_CALLBACK_BRAIN_OAUTH
  | typeof API_CALLBACK_EMAIL_LOGIN
  | typeof API_CALLBACK_PROVIDER_LOGIN
  | typeof API_CLIENTS
  | typeof API_CLIENTS_2
  | typeof API_CLIENTS_ROTATE_SECRET
  | typeof API_LOCALES_JSON
  | typeof API_OAUTH_CONSENT
  | typeof API_OAUTH_PLAYGROUND_VALIDATE
  | typeof API_OAUTH_VERIFY
  | typeof API_PAM_ENVIRONMENTS
  | typeof API_PAM_ENVIRONMENTS_DELETE
  | typeof API_PAM_ENVIRONMENTS_EXPORT
  | typeof API_PAM_ENVIRONMENTS_VARIABLES
  | typeof API_PAM_CATEGORIES
  | typeof API_PAM_CLI_DEVICE_APPROVE
  | typeof API_PAM_CLI_DEVICE_CODE
  | typeof API_PAM_CLI_DEVICE_TOKEN
  | typeof API_PAM_CLI_LOGOUT
  | typeof API_PAM_CLI_TOKEN
  | typeof API_PAM_CREATE
  | typeof API_PAM_DELETE
  | typeof API_PAM_DETAIL
  | typeof API_PAM_EDIT
  | typeof API_PAM_FORK
  | typeof API_PAM_SEARCH
  | typeof API_PAM_TRANSFER
  | typeof API_PAM_USERS_SEARCH
  | typeof API_PAM_PREVIEW_IMAGE
  | typeof API_REFERENCE
  | typeof API_USER_LOGIN
  | typeof API_USER_LOGIN_BRAIN
  | typeof API_USER_LOGIN_PROVIDER
  | typeof API_USER_LOGOUT
  | typeof API_USER_OTP_LOGIN
  | typeof API_USER_OTP_VERIFY
  | typeof API_USER_REGISTER
  | typeof API_USER_REQUEST_LOGS
  | typeof API_USER_SESSION;
