import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { PamCliAuthStoreInterface } from '../interfaces/PamCliAuthStoreInterface';
import type { PamCliLocaleType } from '../interfaces/PamCliTypes';

/**
 * Directory of this module (works for ESM cli bundle and CJS library build).
 */
function getModuleDir(): string {
  // tsup CJS emit provides __dirname; prefer it to avoid empty import.meta.url
  if (typeof __dirname === 'string' && __dirname.length > 0) {
    return __dirname;
  }
  try {
    if (typeof import.meta !== 'undefined' && import.meta.url) {
      return dirname(fileURLToPath(import.meta.url));
    }
  } catch {
    // fall through
  }
  return process.cwd();
}

/**
 * Resolves the pamenv-cli package root (directory containing package.json).
 */
function resolvePackageRoot(): string {
  try {
    const require = createRequire(
      typeof import.meta !== 'undefined' && import.meta.url
        ? import.meta.url
        : join(getModuleDir(), 'noop.js')
    );
    return dirname(require.resolve('pamenv-cli/package.json'));
  } catch {
    // local workspace / not installed as package
  }

  let dir = getModuleDir();
  for (let i = 0; i < 8; i += 1) {
    const pkgPath = join(dir, 'package.json');
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as {
          name?: string;
        };
        if (pkg.name === 'pamenv-cli') {
          return dir;
        }
      } catch {
        // continue walking
      }
    }
    const parent = dirname(dir);
    if (parent === dir) {
      break;
    }
    dir = parent;
  }
  return getModuleDir();
}

/**
 * Dynamic pamenv CLI UX i18n (`pamenv_cli:*`).
 *
 * Significance: Localizes interactive CLI copy without PAM locale pull.
 * Core idea: Load `dist/locales/{locale}.json` generated by ts2locales at runtime.
 * Main function: ensureLoaded / syncFromStore / t(key, vars).
 * Main purpose: en/zh prompts and status lines for login/init/push/pull/config.
 *
 * @example
 * await PamCliI18n.syncFromStore(authStore);
 * console.log(PamCliI18n.t(PAMENV_CLI_LOGIN_WAITING));
 */
export class PamCliI18n {
  protected static locale: PamCliLocaleType = 'en';
  protected static catalogs: Partial<
    Record<PamCliLocaleType, Record<string, string>>
  > = {};
  protected static loadError: string | null = null;

  /**
   * @returns Absolute path to `dist/locales`
   */
  public static getLocalesDir(): string {
    const here = getModuleDir();
    const candidates = [
      join(here, 'locales'),
      join(resolvePackageRoot(), 'dist', 'locales'),
      join(here, '..', 'locales'),
      join(here, '..', 'dist', 'locales')
    ];
    for (const candidate of candidates) {
      if (existsSync(join(candidate, 'en.json'))) {
        return candidate;
      }
    }
    return join(resolvePackageRoot(), 'dist', 'locales');
  }

  /**
   * @param locale - Active CLI locale
   */
  public static setLocale(locale: PamCliLocaleType): void {
    this.locale = locale;
  }

  /**
   * @returns Current in-memory locale
   */
  public static getLocale(): PamCliLocaleType {
    return this.locale;
  }

  /**
   * Loads locale JSON from disk into memory (idempotent per locale).
   *
   * @param locale - Locale to load
   */
  public static async ensureLoaded(
    locale: PamCliLocaleType = this.locale
  ): Promise<void> {
    if (this.catalogs[locale]) {
      return;
    }
    const localesDir = this.getLocalesDir();
    const filePath = join(localesDir, `${locale}.json`);
    try {
      const raw = readFileSync(filePath, 'utf8');
      const parsed = JSON.parse(raw) as unknown;
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        throw new Error(`Invalid locale JSON: ${filePath}`);
      }
      const messages: Record<string, string> = {};
      for (const [key, value] of Object.entries(
        parsed as Record<string, unknown>
      )) {
        if (typeof value === 'string') {
          messages[key] = value;
        }
      }
      this.catalogs[locale] = messages;
      this.loadError = null;
    } catch (error) {
      this.catalogs[locale] = {};
      this.loadError =
        error instanceof Error ? error.message : String(error);
    }
  }

  /**
   * Reads locale from auth store and loads catalogs (active + English fallback).
   *
   * @param authStore - Active config store
   */
  public static async syncFromStore(
    authStore: PamCliAuthStoreInterface
  ): Promise<void> {
    this.locale = await authStore.getLocale();
    await this.ensureLoaded(this.locale);
    if (this.locale !== 'en') {
      await this.ensureLoaded('en');
    }
  }

  /**
   * Looks up a CLI message; falls back to English, then the key.
   *
   * @param key - Message id / identifier constant value
   * @param vars - `{{name}}` replacements
   */
  public static t(
    key: string,
    vars?: Readonly<Record<string, string | number>>
  ): string {
    const primary = this.catalogs[this.locale]?.[key];
    const fallback = this.catalogs.en?.[key];
    const template = primary || fallback || key;
    if (!vars) {
      return template;
    }
    return template.replace(/\{\{(\w+)\}\}/g, (_match, name: string) => {
      const value = vars[name];
      return value === undefined || value === null ? '' : String(value);
    });
  }
}
